---
yum:
  protected: false
  repopath: /opt/
  workers: 2
  createrepoBinary: /bin/createrepo
  rpmBinary: /bin/rpm
  helpFile: /usr/share/doc/yummy/README.md
  auth:
    enabled: false
    user: yummy
    password: yummy
